In [1]:
import numpy as np

In [19]:
import pandas as pd

In [2]:
array=np.random.random(1000)

In [3]:
%timeit sum(array)
%timeit np.sum(array)

156 µs ± 32.9 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
5.32 µs ± 309 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## we can see that numpy array takes less time than a python array 

In [5]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
np.mean(a)

2.0

In [8]:
np.median(a)

2.0

In [9]:
np.std(a)

0.816496580927726

In [10]:
np.var(a)

0.6666666666666666

In [11]:
np.sqrt(np.var(a))

0.816496580927726

In [12]:
# intro of std and var

In [16]:
n1=np.random.randint(20,size=(5,3))

In [20]:
n1

array([[ 8, 14, 13],
       [ 2,  9, 15],
       [ 7, 10,  6],
       [ 0,  5, 18],
       [12,  9,  4]])

In [23]:
sales=pd.DataFrame(n1,index=["car","tree","bottle","diary","laptop"],columns=["number","age","name"])

In [24]:
sales

number  age  name
car          8   14    13
tree         2    9    15
bottle       7   10     6
diary        0    5    18
laptop      12    9     4

In [25]:
np.sort(n1)

array([[ 8, 13, 14],
       [ 2,  9, 15],
       [ 6,  7, 10],
       [ 0,  5, 18],
       [ 4,  9, 12]])